name: 'CI'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        node-version: [23.x, 12.x, 14.x, 16.x, 18.x, 20.x, 22.x, 24.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Run Server tests
        run: npm run test:node
    # We run browser tests only on one version of the node, since client tests do not depend on the server environment.
      - name: Run browser tests
        run: npm run test:browser
        if: matrix.node-version == '22.x'
      - name: Run package tests
        run: npm run test:package

  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: axios-tgz
          path: axios-1.13.2.tgz
          if-no-files-found: error
